num_plan: 5
camera_x: 1.5
camera_z: 2.4
camera_yaws: [0,-30,30]
seg_channels: [4,6,7,10,18]
seg_weight: 0.05
imagenet_pretrained: True
log_wandb: True
noise_collect: False
x_jitter: 3
a_jitter: 15
crop_top: 8
crop_bottom: 8
# Where data collected with q collector relying on trained ego model is saved (rails.data_phase1.py)
main_data_dir: dataset/111121/main
# Location of privileged agent used to train the distilled agent in (lbc.train_phase1.py)
# Note: the privileged agent is saved in the wandb logger_dir (lbc.train_phase0.py)
bev_model_dir: lbc/experiments/111121/bev_model_20.th
# Location of distilled agent used to evaluate model (???.py)
# Note: the distilled agent is saved in the wandb logger_dir (lbc.train_phase1.py)
rgb_model_dir: lbc/experiments/111121/rgb_model_20.th

