#name: world_on_rails
name: cbs2
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  #- cudatoolkit==10.1
  - pip>=21.0
  - python=3.7.9
  #- pytorch==1.4.0
  - pip:
    - dictor
    - lmdb
    - tqdm
    - matplotlib
    - moviepy
    - imageio
    - imageio-ffmpeg
    - imgaug
    - requests
    - opencv-python
    - pyyaml
    - py_trees==0.8.3
    - ray==1.1.0
    - shapely
    - tabulate
    - six
    - wandb
    - xmlschema
    
## Packages installed later:
## 
## - Using local pip of the environment: ~/anaconda3/envs/cbs2/bin/pip install <package>==<version>
##
## torch==1.4.0
## torchvision==0.5.0
## pygame
## ephem
## jupyterlab
## pandas
## aioredis==1.3.1
##
## - Using conda-forge while the environment is activated: conda install -c conda-forge <package>
##
## aiohttp
## 
    
