num_plan: 5
camera_x: 1.5
camera_z: 2.4
#camera_yaws: [0,-30,30]
camera_yaws: [0]
seg_channels: [4,6,7,10,18]
seg_weight: 0.05
imagenet_pretrained: True
log_wandb: True
noise_collect: True
x_jitter: 3
a_jitter: 15
crop_top: 8
crop_bottom: 8
# Where data collected with q collector relying on trained ego model is saved (rails.data_phase1.py)
main_data_dir: dataset/test/main
# Location of privileged agent used to train the distilled agent in (lbc.train_phase1.py)
# Note: the privileged agent is saved in the wandb logger_dir (lbc.train_phase0.py)
bev_model_dir: cbs/reference/bev_model_20.th
# Location of distilled agent used to evaluate model evaluate_nocrash.py)
# Note: the distilled agent is saved in the wandb logger_dir (lbc.train_phase1.py)
#rgb_model_dir_wor: cbs/reference/rgb_model_20.th

#rgb_model_dir: cbs0/reference/fpn-model-100.th
rgb_model_dir: cbs0/reference/ppm-model-5.th
#rgb_model_dir: cbs0/reference/model-5.th

ppm_bins: [1,2,3,6]
#ppm_bins: []

